//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEcostat.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecostatbddEntities : DbContext
    {
        public ecostatbddEntities()
            : base("name=ecostatbddEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<choix> choixes { get; set; }
        public virtual DbSet<enquete> enquetes { get; set; }
        public virtual DbSet<personne> personnes { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<questionnaire> questionnaires { get; set; }
        public virtual DbSet<sondage> sondages { get; set; }
        public virtual DbSet<theme> themes { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visiteur> visiteurs { get; set; }
        public virtual DbSet<questionnairecomplete> questionnairecompletes { get; set; }
    }
}
