//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEcostat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enquete()
        {
            this.questionnaires = new HashSet<questionnaire>();
        }
    
        public int Id { get; set; }
        public int Id_Theme { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public bool disponible { get; set; }
    
        public virtual theme theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionnaire> questionnaires { get; set; }
    }
}
