//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEcostat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnairecomplete
    {
        public Nullable<System.DateTime> dateReponse { get; set; }
        public string localisation { get; set; }
        public int Id_personne { get; set; }
        public int Id_Questionnaire { get; set; }
    
        public virtual personne personne { get; set; }
        public virtual questionnaire questionnaire { get; set; }
    }
}
