//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEcostat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questionnaire()
        {
            this.questions = new HashSet<question>();
            this.sondages = new HashSet<sondage>();
            this.questionnairecompletes = new HashSet<questionnairecomplete>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Titre { get; set; }
        public int Id_Theme { get; set; }
        public bool Disponible { get; set; }
        public Nullable<int> Id_enquete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
        public virtual theme theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sondage> sondages { get; set; }
        public virtual enquete enquete1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionnairecomplete> questionnairecompletes { get; set; }
    }
}
